- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: update
      apt:
        update_cache: yes
        state: latest
    
    - name: Add an Apt signing key,
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: https://download.docker.com/linux/ubuntu
        state: present

    - name: update
      apt:
        update_cache: yes
        state: latest
    - name: To install 
      apt:
        name: docker-ce
        state: present
    - name: Start the docker
      service:
        name: docker
        state: started

    
    