- hosts: all
  remote_user: ubuntu
  become: yes
  vars_files:
    valtpass.yml
  tasks:
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: "{{ username }} & {{ password }}"
  