- hosts: b
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Update repositories cache and install "foo" package
    ansible.builtin.apt:
     name: '*'
     update_cache: yes
  - name:
    ansible.builtin.apt:
      name: openjdk-21-jdk-headless
      state: present
  - name: Download Tomcat
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.28/bin/apache-tomcat-10.1.28.tar.gz
      dest: /opt
  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /opt/apache-tomcat-10.1.28.tar.gz
      dest: /opt
      remote_src: yes
  - name: Execute the command in remote shell
    ansible.builtin.shell: /opt/apache-tomcat-10.1.28/bin/startup.sh &

  
